{"WARN": 12, "filename": "5_5_do_not_return_from_finally_warning_.py", "lineno": 9, "message": "'return' in finally block may swallow exception", "warnline": "    return 0"}
